language: python
# install dependencies
install:
  - make
# run tests
script:
  - make ci
cache: pip
jobs:
  include:
    - stage: test
      script:
        - make ci
      python: '3.6'
    - stage: test
      script:
        - make ci
      python: '3.7'
      dist: xenial
    - stage: coverage
      script:
        - make coverage
        - codecov
      python: '3.7'
      dist: xenial
